# Generated by Django 4.0.3 on 2022-03-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_filial_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='bank.bank'),
        ),
    ]
