# Generated by Django 4.0.3 on 2022-03-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Information technologies', 'Information technologies'), ('Menegment', 'Menegment'), ('Seller', 'Seller'), ('Cashier', 'Cashier'), ('Interner', 'Interner')], max_length=100)),
                ('profilpicture', models.ImageField(upload_to='accountsPictures/')),
                ('salary', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
